export const state = {
  authUiEnabled: true,
  telegramAuthEnabled: false,
  adminMode: false,
  authUser: null,
  authChecked: false,
  authLoginOpen: false,
	authMode: "login",
	registrationPlayers: [],
	registrationPlayersLoading: false,
	account: null,
	accountOnboardingRequired: false,
	accountPlayers: [],
  accountAvailablePlayers: [],
	accountLoading: false,
	adminAccounts: [],
	adminAccountsLoading: false,
	adminAccountsQuery: "",
  guestPlayerId: "",
  guestPlayers: [],

  activeSessionId: "",
  session: null,

  localRuntimeStatus: "uninitialized",
  localRuntimeError: "",
  sessionDataSource: "none",
  sessionCachedAt: null,
  sessionRefreshStatus: "idle",
  sessionLocalRevision: 0,
  sessionExpensesCached: false,
  sessionSettlementsCached: false,
  sessionReplayStatus: "idle",
  sessionPendingCount: 0,
  sessionBlockedCount: 0,
  sessionLastSuccessfulReplayAt: null,
  sessionReplayError: null,
  localFirstSessionWritesEnabled: false,
  localFirstSessionWritesFlagSource: "uninitialized",

  overviewSessions: [],
  overviewSessionPageItems: [],
  overviewSessionsFilter: "all",
  overviewSessionsPage: 0,
  overviewSessionsPageSize: 20,
  overviewSessionsHasNextPage: false,
  overviewPlayers: [],
  overviewPlayersAll: [],
  overviewPlayersSort: "last_activity",
  overviewPlayersShowAll: false,
  overviewActiveRecentPlayerIds: new Set(),
  playersStatsRows: [],

  players: [],
  sessionPlayerActionMode: "rebuy",
  expensePayerMode: "even",
  expenseParticipantMode: "all",
  expenseFormOpen: false,
  operations: [],
  expenses: [],
  settlementDrafts: {},
  settlementEditing: false,

  // player screen
  selectedPlayerId: "",
  selectedPlayerDetail: null,
  selectedPlayerFilters: {
    from: "",
    to: "",
  },
};
