export const state = {
  authUiEnabled: false,
  adminMode: false,
  authUser: null,
  authChecked: false,
  authLoginOpen: false,
  accountPlayers: [],
  accountAvailablePlayers: [],
  accountLoading: false,
  guestPlayerId: "",
  guestPlayers: [],

  activeSessionId: "",
  session: null,

  localRuntimeStatus: "uninitialized",
  localRuntimeError: "",
  sessionDataSource: "none",
  sessionCachedAt: null,
  sessionRefreshStatus: "idle",
  sessionLocalRevision: 0,
  sessionExpensesCached: false,
  sessionSettlementsCached: false,
  sessionReplayStatus: "idle",
  sessionPendingCount: 0,
  sessionBlockedCount: 0,
  sessionLastSuccessfulReplayAt: null,
  sessionReplayError: null,
  localFirstSessionWritesEnabled: false,
  localFirstSessionWritesFlagSource: "uninitialized",

  overviewSessions: [],
  overviewSessionsFilter: "all",
  overviewPlayers: [],
  overviewPlayersAll: [],
  overviewPlayersSort: "last_activity",
  overviewPlayersShowAll: false,
  overviewActiveRecentPlayerIds: new Set(),
  playersStatsRows: [],

  players: [],
  sessionPlayerActionMode: "rebuy",
  expensePayerMode: "even",
  expenseParticipantMode: "all",
  expenseFormOpen: false,
  operations: [],
  expenses: [],
  settlementDrafts: {},
  settlementEditing: false,

  // player screen
  selectedPlayerId: "",
  selectedPlayerDetail: null,
  selectedPlayerFilters: {
    from: "",
    to: "",
  },
};
